# Generated by Django 2.1.3 on 2018-11-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('goods_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('goods_number', models.IntegerField()),
                ('goods_price', models.FloatField()),
            ],
        ),
    ]
