# Generated by Django 2.1.3 on 2018-11-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_goodsinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品管理'},
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_sales',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
    ]
